// <auto-generated />
using System;
using DashyDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DashyDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617160904_AddScreenshotRequiredToClientTools")]
    partial class AddScreenshotRequiredToClientTools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.AttestationLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("AssociateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<int>("CycleID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToolCount")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("CycleID");

                    b.ToTable("AttestationLogs", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Client", b =>
                {
                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClientDesc")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ClientID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.Property<int>("ToolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ToolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToolID"));

                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("ScreenshotRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ToolName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ToolName");

                    b.HasKey("ToolID");

                    b.HasIndex("ClientID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("ClientTools", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Cycle", b =>
                {
                    b.Property<int>("CycleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CycleID"));

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("CycleID");

                    b.ToTable("Cycles", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.LoginLog", b =>
                {
                    b.Property<int>("LoginLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginLogID"));

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoginLogID");

                    b.ToTable("LoginLogs", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.SuperUser", b =>
                {
                    b.Property<int>("SuperUserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperUserID"));

                    b.Property<string>("AccessLevel")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssociateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SuperUserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("AssociateId", "RoleName", "DepartmentID")
                        .IsUnique()
                        .HasFilter("[DepartmentID] IS NOT NULL");

                    b.ToTable("SuperUsers", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ToolCycleAttestation", b =>
                {
                    b.Property<int>("CycleID")
                        .HasColumnType("int");

                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToolID")
                        .HasColumnType("int");

                    b.Property<string>("AttestationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<bool>("HadAccess")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScreenshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ScreenshotRejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ScreenshotReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ScreenshotReviewedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ScreenshotStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ScreenshotUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UsedThisCycle")
                        .HasColumnType("bit");

                    b.HasKey("CycleID", "AssociateId", "ClientID", "ToolID");

                    b.HasIndex("AssociateId");

                    b.ToTable("ToolCycleAttestation", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.User", b =>
                {
                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("Department")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmailAddr")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMailAddr");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PrimaryLocationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssociateId");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.UserToolAccess", b =>
                {
                    b.Property<string>("AssociateId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("AssociateID");

                    b.Property<string>("ClientID")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ToolID")
                        .HasColumnType("int");

                    b.Property<bool>("Access")
                        .HasColumnType("bit");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("date")
                        .HasColumnName("GivenDate");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("date");

                    b.Property<string>("ToolUserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AssociateId", "ClientID", "ToolID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("ToolID");

                    b.ToTable("UsersToolAccess", (string)null);
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.AttestationLog", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.Client", "Client")
                        .WithMany("Tools")
                        .HasForeignKey("ClientID");

                    b.HasOne("DashyDashboard.Api.Models.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Client");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.SuperUser", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.Department", "Department")
                        .WithMany("SuperUsers")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ToolCycleAttestation", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("AssociateId");

                    b.HasOne("DashyDashboard.Api.Models.Domain.Cycle", "Cycle")
                        .WithMany("Attestations")
                        .HasForeignKey("CycleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.UserToolAccess", b =>
                {
                    b.HasOne("DashyDashboard.Api.Models.Domain.User", "User")
                        .WithMany("ToolAccess")
                        .HasForeignKey("AssociateId");

                    b.HasOne("DashyDashboard.Api.Models.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID");

                    b.HasOne("DashyDashboard.Api.Models.Domain.ClientTool", "ClientTool")
                        .WithMany("UserAccess")
                        .HasForeignKey("ToolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientTool");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Client", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.ClientTool", b =>
                {
                    b.Navigation("UserAccess");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Cycle", b =>
                {
                    b.Navigation("Attestations");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.Department", b =>
                {
                    b.Navigation("SuperUsers");
                });

            modelBuilder.Entity("DashyDashboard.Api.Models.Domain.User", b =>
                {
                    b.Navigation("ToolAccess");
                });
#pragma warning restore 612, 618
        }
    }
}
